# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Official

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: 
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]

env:
  GB_NUGET_TOKEN: ${{secrets.GB_NUGET_TOKEN}}
  MS_NUGET_TOKEN: ${{secrets.MS_NUGET_TOKEN}}
  SYZERO_CORE_BRANCH: dev1.1.3

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: syzero-authorization-service

      - name: Checkout syzero-core repo
        uses: actions/checkout@v3
        with:
          repository: winter2048/syzero-core
          path: syzero-core
          ref: ${{ env.SYZERO_CORE_BRANCH }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./syzero-authorization-service/src/SyZero.Authorization.sln

      - name: Build
        run: dotnet build --configuration Release ./syzero-authorization-service/src/SyZero.Authorization.sln --no-restore

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ./syzero-authorization-service/src/SyZero.Authorization.Web/bin/*

      # - name: Commit app
      #   run: |
      #     cd syzero-authorization-service
      #     $gf=$(git diff)
      #     if ("$gf" -ne "") {
      #       echo "IS_GIT_CHANGE=true" >> $env:GITHUB_ENV
      #       git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #       git config --global user.name "github-actions[bot]"
      #       git add .
      #       git commit -m "update app" -a
      #     } else {
      #       echo "IS_GIT_CHANGE=false" >> $env:GITHUB_ENV
      #     }
      #   shell: powershell

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   if: env.IS_GIT_CHANGE == 'true'
      #   with:
      #     github_token: ${{ secrets.GB_NUGET_TOKEN }}
      #     directory: ./syzero-authorization-service
      #     branch: ${{ github.ref }}
      #     force: true

  pushImage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: harbor.syzero.com
          username: ${{ secrets.HARBOR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKERHUB_TOKEN }}

      - name: Build and push (master)
        uses: docker/build-push-action@v4
        if: github.ref_name == 'master'
        with:
          context: ./Release/net9.0/
          push: true
          tags: |
            harbor.syzero.com/syzero/syzero.authorization.service:latest
            harbor.syzero.com/syzero/syzero.authorization.service:${{ github.run_number }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v4
        if: github.ref_name == 'dev'
        with:
          context: ./Release/net9.0/
          push: true
          tags: |
            harbor.syzero.com/syzero/syzero.authorization.service:dev
            harbor.syzero.com/syzero/syzero.authorization.service:${{ github.run_number }}-dev